/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalahRouteImport } from './routes/salah'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyAdhkarRouteImport } from './routes/my-adhkar'
import { Route as MoreRouteImport } from './routes/more'
import { Route as EveningRouteImport } from './routes/evening'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalahRoute = SalahRouteImport.update({
  id: '/salah',
  path: '/salah',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAdhkarRoute = MyAdhkarRouteImport.update({
  id: '/my-adhkar',
  path: '/my-adhkar',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const EveningRoute = EveningRouteImport.update({
  id: '/evening',
  path: '/evening',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/evening': typeof EveningRoute
  '/more': typeof MoreRoute
  '/my-adhkar': typeof MyAdhkarRoute
  '/privacy': typeof PrivacyRoute
  '/qibla': typeof QiblaRoute
  '/salah': typeof SalahRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/tasbih': typeof TasbihRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/evening': typeof EveningRoute
  '/more': typeof MoreRoute
  '/my-adhkar': typeof MyAdhkarRoute
  '/privacy': typeof PrivacyRoute
  '/qibla': typeof QiblaRoute
  '/salah': typeof SalahRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/tasbih': typeof TasbihRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/evening': typeof EveningRoute
  '/more': typeof MoreRoute
  '/my-adhkar': typeof MyAdhkarRoute
  '/privacy': typeof PrivacyRoute
  '/qibla': typeof QiblaRoute
  '/salah': typeof SalahRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/tasbih': typeof TasbihRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/evening'
    | '/more'
    | '/my-adhkar'
    | '/privacy'
    | '/qibla'
    | '/salah'
    | '/settings'
    | '/sleep'
    | '/tasbih'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/evening'
    | '/more'
    | '/my-adhkar'
    | '/privacy'
    | '/qibla'
    | '/salah'
    | '/settings'
    | '/sleep'
    | '/tasbih'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/evening'
    | '/more'
    | '/my-adhkar'
    | '/privacy'
    | '/qibla'
    | '/salah'
    | '/settings'
    | '/sleep'
    | '/tasbih'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EveningRoute: typeof EveningRoute
  MoreRoute: typeof MoreRoute
  MyAdhkarRoute: typeof MyAdhkarRoute
  PrivacyRoute: typeof PrivacyRoute
  QiblaRoute: typeof QiblaRoute
  SalahRoute: typeof SalahRoute
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  TasbihRoute: typeof TasbihRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salah': {
      id: '/salah'
      path: '/salah'
      fullPath: '/salah'
      preLoaderRoute: typeof SalahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-adhkar': {
      id: '/my-adhkar'
      path: '/my-adhkar'
      fullPath: '/my-adhkar'
      preLoaderRoute: typeof MyAdhkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evening': {
      id: '/evening'
      path: '/evening'
      fullPath: '/evening'
      preLoaderRoute: typeof EveningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EveningRoute: EveningRoute,
  MoreRoute: MoreRoute,
  MyAdhkarRoute: MyAdhkarRoute,
  PrivacyRoute: PrivacyRoute,
  QiblaRoute: QiblaRoute,
  SalahRoute: SalahRoute,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  TasbihRoute: TasbihRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
