/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalahRouteImport } from './routes/salah'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as MoreRouteImport } from './routes/more'
import { Route as EveningRouteImport } from './routes/evening'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMyAdhkarRouteImport } from './routes/_authenticated/my-adhkar'

const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalahRoute = SalahRouteImport.update({
  id: '/salah',
  path: '/salah',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const EveningRoute = EveningRouteImport.update({
  id: '/evening',
  path: '/evening',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyAdhkarRoute = AuthenticatedMyAdhkarRouteImport.update({
  id: '/my-adhkar',
  path: '/my-adhkar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/evening': typeof EveningRoute
  '/more': typeof MoreRoute
  '/qibla': typeof QiblaRoute
  '/salah': typeof SalahRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/tasbih': typeof TasbihRoute
  '/my-adhkar': typeof AuthenticatedMyAdhkarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/evening': typeof EveningRoute
  '/more': typeof MoreRoute
  '/qibla': typeof QiblaRoute
  '/salah': typeof SalahRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/tasbih': typeof TasbihRoute
  '/my-adhkar': typeof AuthenticatedMyAdhkarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/evening': typeof EveningRoute
  '/more': typeof MoreRoute
  '/qibla': typeof QiblaRoute
  '/salah': typeof SalahRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/tasbih': typeof TasbihRoute
  '/_authenticated/my-adhkar': typeof AuthenticatedMyAdhkarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/evening'
    | '/more'
    | '/qibla'
    | '/salah'
    | '/settings'
    | '/sleep'
    | '/tasbih'
    | '/my-adhkar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/evening'
    | '/more'
    | '/qibla'
    | '/salah'
    | '/settings'
    | '/sleep'
    | '/tasbih'
    | '/my-adhkar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/evening'
    | '/more'
    | '/qibla'
    | '/salah'
    | '/settings'
    | '/sleep'
    | '/tasbih'
    | '/_authenticated/my-adhkar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EveningRoute: typeof EveningRoute
  MoreRoute: typeof MoreRoute
  QiblaRoute: typeof QiblaRoute
  SalahRoute: typeof SalahRoute
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  TasbihRoute: typeof TasbihRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salah': {
      id: '/salah'
      path: '/salah'
      fullPath: '/salah'
      preLoaderRoute: typeof SalahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evening': {
      id: '/evening'
      path: '/evening'
      fullPath: '/evening'
      preLoaderRoute: typeof EveningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-adhkar': {
      id: '/_authenticated/my-adhkar'
      path: '/my-adhkar'
      fullPath: '/my-adhkar'
      preLoaderRoute: typeof AuthenticatedMyAdhkarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyAdhkarRoute: typeof AuthenticatedMyAdhkarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyAdhkarRoute: AuthenticatedMyAdhkarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EveningRoute: EveningRoute,
  MoreRoute: MoreRoute,
  QiblaRoute: QiblaRoute,
  SalahRoute: SalahRoute,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  TasbihRoute: TasbihRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
